export const RDV_CREATE_REQUEST = 'RDV_CREATE_REQUEST';
export const RDV_CREATE_SUCCESS = 'RDV_CREATE_SUCCESS';
export const RDV_CREATE_FAIL = 'RDV_CREATE_FAIL';

export const RDV_DETAILS_REQUEST = 'RDV_DETAILS_REQUEST';
export const RDV_DETAILS_SUCCESS = 'RDV_DETAILS_SUCCESS';
export const RDV_DETAILS_FAIL = 'RDV_DETAILS_FAIL';
