export const RDV_ADD_DOCTOR = 'RDV_ADD_DOCTOR';

export const RDV_ADD_DATE = 'RDV_SAVE_DATE';

export const RDV_ADD_RENSEIGNEMETS = 'RDV_ADD_RENSEIGNEMETS';

export const RDV_ADD_PAYMENT_METHOD = 'RDV_ADD_PAYMENT_METHOD';
